default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: neural
  password: 'admin1234'

development:
  <<: *default
  database: col_san_fernando_development

staging:
  <<: *default
  database: col_san_fernando_staging
#

test:
  <<: *default
  database: col_san_fernando_test
#
production:
  <<: *default
  database: col_san_fernando_production
  username: col_san_fernando
  password: <%= ENV['COL_SAN_FERNANDO_DATABASE_PASSWORD'] %>